version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.11
    - 8.2.12
  - dependency-name: webpack
    versions:
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.26.0
    - 5.26.1
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.1
    - 5.27.2
  - dependency-name: css-loader
    versions:
    - 5.1.3
